ArmPkg/ArmStandaloneMmCoreEntryPoint: Fix clang build issues (#338)
## Description

Will upstream to edk2 but need here now to unblock updating QemuSbsaPkg.

---

**Issue 1:**

```
error: immediate must be an integer in range [0, 65535].
movz x9, (-1) >> 48, lsl #48
movk x9, ((-1) >> 32) & 0xffff, lsl #32
movk x9, ((-1) >> 16) & 0xffff, lsl #16
movk x9, (-1) & 0xffff
```

From this code in ModuleEntryPoint.S:

```
  MOV64 (x9, ARM_FFA_RET_NOT_SUPPORTED)
```

The change uses `xzr` with the `mvn` instruction to set the register to
`-1`.

---

**Issue 2:**

Pointer cast issues such as:

```
ArmStandaloneMmCoreEntryPoint.c:1041:48: error: cast to smaller
  integer type 'unsigned long' from 'void *'
  [-Werror,-Wvoid-pointer-to-int-cast]

  1041 |   DEBUG ((DEBUG_INFO, "Start Dump Hob: %lx\n",
             (unsigned long)HobStart));
```

The `%p` specifer is now used to print the pointers.

---

- [x] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?
- [x] Backport to release branch?

## How This Was Tested

- QemuSbsaPkg CLANGPDB build with the file present
- `stuart_build -c Platforms/QemuSbsaPkg/PlatformBuild.py
TOOL_CHAIN_TAG=CLANGPDB TARGET=DEBUG`

## Integration Instructions

- N/A

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>
(cherry picked from commit 0d3a9055596f83d17a769917b3acfc2d4b09e764)