ArmPkg/ArmStandaloneMmCoreEntryPoint: Fix clang build issues
Issue 1:

```
error: immediate must be an integer in range [0, 65535].
movz x9, (-1) >> 48, lsl #48
movk x9, ((-1) >> 32) & 0xffff, lsl #32
movk x9, ((-1) >> 16) & 0xffff, lsl #16
movk x9, (-1) & 0xffff
```

From this codee in ModuleEntryPoint.S:

```
  MOV64 (x9, ARM_FFA_RET_NOT_SUPPORTED)
```

The change is to move `0` into `x9` which will zero the full 64-bit
register as `mov` is an alias of `movz`. Then `mvn` is used to invert
the bits to -1.

---

Issue 2:

Pointer cast issues such as:

```
ArmStandaloneMmCoreEntryPoint.c:1041:48: error: cast to smaller
  integer type 'unsigned long' from 'void *'
  [-Werror,-Wvoid-pointer-to-int-cast]

  1041 |   DEBUG ((DEBUG_INFO, "Start Dump Hob: %lx\n",
             (unsigned long)HobStart));
```

The `%p` specifer is now used to print the pointers.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>